//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProjectDesigner.Data", "FK_VMS_Foundation", "Foundation", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectDesigner.Data.Foundation), "VM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectDesigner.Data.VMS), true)]
[assembly: EdmRelationshipAttribute("ProjectDesigner.Data", "FK_VMS_LEDModule", "LEDModule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectDesigner.Data.LEDModule), "VM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectDesigner.Data.VMS), true)]
[assembly: EdmRelationshipAttribute("ProjectDesigner.Data", "FK_Navigators_Navigators", "Navigator", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectDesigner.Data.Navigator), "Navigator1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectDesigner.Data.Navigator), true)]
[assembly: EdmRelationshipAttribute("ProjectDesigner.Data", "FK_VMS_Pillar", "Pillar", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProjectDesigner.Data.Pillar), "VM", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProjectDesigner.Data.VMS), true)]

#endregion

namespace ProjectDesigner.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EntityContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EntityContext object using the connection string found in the 'EntityContext' section of the application configuration file.
        /// </summary>
        public EntityContext() : base("name=EntityContext", "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityContext object.
        /// </summary>
        public EntityContext(string connectionString) : base(connectionString, "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EntityContext object.
        /// </summary>
        public EntityContext(EntityConnection connection) : base(connection, "EntityContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BizModule> BizModules
        {
            get
            {
                if ((_BizModules == null))
                {
                    _BizModules = base.CreateObjectSet<BizModule>("BizModules");
                }
                return _BizModules;
            }
        }
        private ObjectSet<BizModule> _BizModules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<File> Files
        {
            get
            {
                if ((_Files == null))
                {
                    _Files = base.CreateObjectSet<File>("Files");
                }
                return _Files;
            }
        }
        private ObjectSet<File> _Files;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Foundation> Foundations
        {
            get
            {
                if ((_Foundations == null))
                {
                    _Foundations = base.CreateObjectSet<Foundation>("Foundations");
                }
                return _Foundations;
            }
        }
        private ObjectSet<Foundation> _Foundations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LEDModule> LEDModules
        {
            get
            {
                if ((_LEDModules == null))
                {
                    _LEDModules = base.CreateObjectSet<LEDModule>("LEDModules");
                }
                return _LEDModules;
            }
        }
        private ObjectSet<LEDModule> _LEDModules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Navigator> Navigators
        {
            get
            {
                if ((_Navigators == null))
                {
                    _Navigators = base.CreateObjectSet<Navigator>("Navigators");
                }
                return _Navigators;
            }
        }
        private ObjectSet<Navigator> _Navigators;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pillar> Pillars
        {
            get
            {
                if ((_Pillars == null))
                {
                    _Pillars = base.CreateObjectSet<Pillar>("Pillars");
                }
                return _Pillars;
            }
        }
        private ObjectSet<Pillar> _Pillars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VMS> VMS
        {
            get
            {
                if ((_VMS == null))
                {
                    _VMS = base.CreateObjectSet<VMS>("VMS");
                }
                return _VMS;
            }
        }
        private ObjectSet<VMS> _VMS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Projects
        {
            get
            {
                if ((_Projects == null))
                {
                    _Projects = base.CreateObjectSet<Project>("Projects");
                }
                return _Projects;
            }
        }
        private ObjectSet<Project> _Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProjectEquipment> ProjectEquipments
        {
            get
            {
                if ((_ProjectEquipments == null))
                {
                    _ProjectEquipments = base.CreateObjectSet<ProjectEquipment>("ProjectEquipments");
                }
                return _ProjectEquipments;
            }
        }
        private ObjectSet<ProjectEquipment> _ProjectEquipments;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BizModules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBizModules(BizModule bizModule)
        {
            base.AddObject("BizModules", bizModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Files EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Foundations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoundations(Foundation foundation)
        {
            base.AddObject("Foundations", foundation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LEDModules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLEDModules(LEDModule lEDModule)
        {
            base.AddObject("LEDModules", lEDModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Navigators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNavigators(Navigator navigator)
        {
            base.AddObject("Navigators", navigator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pillars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPillars(Pillar pillar)
        {
            base.AddObject("Pillars", pillar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VMS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVMS(VMS vMS)
        {
            base.AddObject("VMS", vMS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjects(Project project)
        {
            base.AddObject("Projects", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProjectEquipments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProjectEquipments(ProjectEquipment projectEquipment)
        {
            base.AddObject("ProjectEquipments", projectEquipment);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="BizModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BizModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BizModule object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isProtected">Initial value of the IsProtected property.</param>
        public static BizModule CreateBizModule(global::System.String id, global::System.String name, global::System.Boolean isProtected)
        {
            BizModule bizModule = new BizModule();
            bizModule.Id = id;
            bizModule.Name = name;
            bizModule.IsProtected = isProtected;
            return bizModule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsProtected
        {
            get
            {
                return _IsProtected;
            }
            set
            {
                OnIsProtectedChanging(value);
                ReportPropertyChanging("IsProtected");
                _IsProtected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProtected");
                OnIsProtectedChanged();
            }
        }
        private global::System.Boolean _IsProtected;
        partial void OnIsProtectedChanging(global::System.Boolean value);
        partial void OnIsProtectedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="File")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class File : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="uploadedTime">Initial value of the UploadedTime property.</param>
        public static File CreateFile(global::System.String id, global::System.String name, global::System.String fileName, global::System.DateTime uploadedTime)
        {
            File file = new File();
            file.Id = id;
            file.Name = name;
            file.FileName = fileName;
            file.UploadedTime = uploadedTime;
            return file;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tags
        {
            get
            {
                return _Tags;
            }
            set
            {
                OnTagsChanging(value);
                ReportPropertyChanging("Tags");
                _Tags = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tags");
                OnTagsChanged();
            }
        }
        private global::System.String _Tags;
        partial void OnTagsChanging(global::System.String value);
        partial void OnTagsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UploadedTime
        {
            get
            {
                return _UploadedTime;
            }
            set
            {
                OnUploadedTimeChanging(value);
                ReportPropertyChanging("UploadedTime");
                _UploadedTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UploadedTime");
                OnUploadedTimeChanged();
            }
        }
        private global::System.DateTime _UploadedTime;
        partial void OnUploadedTimeChanging(global::System.DateTime value);
        partial void OnUploadedTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="Foundation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Foundation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Foundation object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Foundation CreateFoundation(global::System.String id)
        {
            Foundation foundation = new Foundation();
            foundation.Id = id;
            return foundation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EquipmentType;
        partial void OnEquipmentTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEquipmentTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_Foundation", "VM")]
        public EntityCollection<VMS> VMS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_Foundation", "VM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_Foundation", "VM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="LEDModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LEDModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LEDModule object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static LEDModule CreateLEDModule(global::System.String id)
        {
            LEDModule lEDModule = new LEDModule();
            lEDModule.Id = id;
            return lEDModule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Standard
        {
            get
            {
                return _Standard;
            }
            set
            {
                OnStandardChanging(value);
                ReportPropertyChanging("Standard");
                _Standard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Standard");
                OnStandardChanged();
            }
        }
        private Nullable<global::System.Int32> _Standard;
        partial void OnStandardChanging(Nullable<global::System.Int32> value);
        partial void OnStandardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EquipmentType;
        partial void OnEquipmentTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEquipmentTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_LEDModule", "VM")]
        public EntityCollection<VMS> VMS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_LEDModule", "VM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_LEDModule", "VM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="Navigator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Navigator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Navigator object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sortIndex">Initial value of the SortIndex property.</param>
        public static Navigator CreateNavigator(global::System.String id, global::System.Int32 sortIndex)
        {
            Navigator navigator = new Navigator();
            navigator.Id = id;
            navigator.SortIndex = sortIndex;
            return navigator;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parent_Id
        {
            get
            {
                return _Parent_Id;
            }
            set
            {
                OnParent_IdChanging(value);
                ReportPropertyChanging("Parent_Id");
                _Parent_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parent_Id");
                OnParent_IdChanged();
            }
        }
        private global::System.String _Parent_Id;
        partial void OnParent_IdChanging(global::System.String value);
        partial void OnParent_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LayoutName
        {
            get
            {
                return _LayoutName;
            }
            set
            {
                OnLayoutNameChanging(value);
                ReportPropertyChanging("LayoutName");
                _LayoutName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LayoutName");
                OnLayoutNameChanged();
            }
        }
        private global::System.String _LayoutName;
        partial void OnLayoutNameChanging(global::System.String value);
        partial void OnLayoutNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebLink
        {
            get
            {
                return _WebLink;
            }
            set
            {
                OnWebLinkChanging(value);
                ReportPropertyChanging("WebLink");
                _WebLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebLink");
                OnWebLinkChanged();
            }
        }
        private global::System.String _WebLink;
        partial void OnWebLinkChanging(global::System.String value);
        partial void OnWebLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WinLink
        {
            get
            {
                return _WinLink;
            }
            set
            {
                OnWinLinkChanging(value);
                ReportPropertyChanging("WinLink");
                _WinLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WinLink");
                OnWinLinkChanged();
            }
        }
        private global::System.String _WinLink;
        partial void OnWinLinkChanging(global::System.String value);
        partial void OnWinLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WapLink
        {
            get
            {
                return _WapLink;
            }
            set
            {
                OnWapLinkChanging(value);
                ReportPropertyChanging("WapLink");
                _WapLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WapLink");
                OnWapLinkChanged();
            }
        }
        private global::System.String _WapLink;
        partial void OnWapLinkChanging(global::System.String value);
        partial void OnWapLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Parameters
        {
            get
            {
                return _Parameters;
            }
            set
            {
                OnParametersChanging(value);
                ReportPropertyChanging("Parameters");
                _Parameters = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Parameters");
                OnParametersChanged();
            }
        }
        private global::System.String _Parameters;
        partial void OnParametersChanging(global::System.String value);
        partial void OnParametersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortIndex
        {
            get
            {
                return _SortIndex;
            }
            set
            {
                OnSortIndexChanging(value);
                ReportPropertyChanging("SortIndex");
                _SortIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortIndex");
                OnSortIndexChanged();
            }
        }
        private global::System.Int32 _SortIndex;
        partial void OnSortIndexChanging(global::System.Int32 value);
        partial void OnSortIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IconFile
        {
            get
            {
                return _IconFile;
            }
            set
            {
                OnIconFileChanging(value);
                ReportPropertyChanging("IconFile");
                _IconFile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IconFile");
                OnIconFileChanged();
            }
        }
        private global::System.String _IconFile;
        partial void OnIconFileChanging(global::System.String value);
        partial void OnIconFileChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_Navigators_Navigators", "Navigator1")]
        public EntityCollection<Navigator> ChildNavigators
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_Navigators_Navigators", "Navigator")]
        public Navigator Parent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Navigator> ParentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Navigator>("ProjectDesigner.Data.FK_Navigators_Navigators", "Navigator", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="Pillar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pillar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pillar object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Pillar CreatePillar(global::System.String id)
        {
            Pillar pillar = new Pillar();
            pillar.Id = id;
            return pillar;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Double> _Height;
        partial void OnHeightChanging(Nullable<global::System.Double> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Diameter
        {
            get
            {
                return _Diameter;
            }
            set
            {
                OnDiameterChanging(value);
                ReportPropertyChanging("Diameter");
                _Diameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diameter");
                OnDiameterChanged();
            }
        }
        private Nullable<global::System.Double> _Diameter;
        partial void OnDiameterChanging(Nullable<global::System.Double> value);
        partial void OnDiameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Double> _Length;
        partial void OnLengthChanging(Nullable<global::System.Double> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EquipmentType;
        partial void OnEquipmentTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEquipmentTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_Pillar", "VM")]
        public EntityCollection<VMS> VMS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_Pillar", "VM");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<VMS>("ProjectDesigner.Data.FK_VMS_Pillar", "VM", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Project CreateProject(global::System.String id)
        {
            Project project = new Project();
            project.Id = id;
            return project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="ProjectEquipment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProjectEquipment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProjectEquipment object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ProjectEquipment CreateProjectEquipment(global::System.String id, global::System.String name)
        {
            ProjectEquipment projectEquipment = new ProjectEquipment();
            projectEquipment.Id = id;
            projectEquipment.Name = name;
            return projectEquipment;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EquipmentType;
        partial void OnEquipmentTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEquipmentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProjectId
        {
            get
            {
                return _ProjectId;
            }
            set
            {
                OnProjectIdChanging(value);
                ReportPropertyChanging("ProjectId");
                _ProjectId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProjectId");
                OnProjectIdChanged();
            }
        }
        private global::System.String _ProjectId;
        partial void OnProjectIdChanging(global::System.String value);
        partial void OnProjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectDesigner.Data", Name="VMS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VMS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VMS object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static VMS CreateVMS(global::System.String id)
        {
            VMS vMS = new VMS();
            vMS.Id = id;
            return vMS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Connection
        {
            get
            {
                return _Connection;
            }
            set
            {
                OnConnectionChanging(value);
                ReportPropertyChanging("Connection");
                _Connection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Connection");
                OnConnectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Connection;
        partial void OnConnectionChanging(Nullable<global::System.Int32> value);
        partial void OnConnectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.String _Size;
        partial void OnSizeChanging(global::System.String value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Double> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Double> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModuleCount
        {
            get
            {
                return _ModuleCount;
            }
            set
            {
                OnModuleCountChanging(value);
                ReportPropertyChanging("ModuleCount");
                _ModuleCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleCount");
                OnModuleCountChanged();
            }
        }
        private Nullable<global::System.Int32> _ModuleCount;
        partial void OnModuleCountChanging(Nullable<global::System.Int32> value);
        partial void OnModuleCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IconPath
        {
            get
            {
                return _IconPath;
            }
            set
            {
                OnIconPathChanging(value);
                ReportPropertyChanging("IconPath");
                _IconPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IconPath");
                OnIconPathChanged();
            }
        }
        private global::System.String _IconPath;
        partial void OnIconPathChanging(global::System.String value);
        partial void OnIconPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LEDModuleId
        {
            get
            {
                return _LEDModuleId;
            }
            set
            {
                OnLEDModuleIdChanging(value);
                ReportPropertyChanging("LEDModuleId");
                _LEDModuleId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LEDModuleId");
                OnLEDModuleIdChanged();
            }
        }
        private global::System.String _LEDModuleId;
        partial void OnLEDModuleIdChanging(global::System.String value);
        partial void OnLEDModuleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PillarId
        {
            get
            {
                return _PillarId;
            }
            set
            {
                OnPillarIdChanging(value);
                ReportPropertyChanging("PillarId");
                _PillarId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PillarId");
                OnPillarIdChanged();
            }
        }
        private global::System.String _PillarId;
        partial void OnPillarIdChanging(global::System.String value);
        partial void OnPillarIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FoundationId
        {
            get
            {
                return _FoundationId;
            }
            set
            {
                OnFoundationIdChanging(value);
                ReportPropertyChanging("FoundationId");
                _FoundationId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FoundationId");
                OnFoundationIdChanged();
            }
        }
        private global::System.String _FoundationId;
        partial void OnFoundationIdChanging(global::System.String value);
        partial void OnFoundationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EquipmentType
        {
            get
            {
                return _EquipmentType;
            }
            set
            {
                OnEquipmentTypeChanging(value);
                ReportPropertyChanging("EquipmentType");
                _EquipmentType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EquipmentType");
                OnEquipmentTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _EquipmentType;
        partial void OnEquipmentTypeChanging(Nullable<global::System.Int32> value);
        partial void OnEquipmentTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_Foundation", "Foundation")]
        public Foundation Foundation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foundation>("ProjectDesigner.Data.FK_VMS_Foundation", "Foundation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foundation>("ProjectDesigner.Data.FK_VMS_Foundation", "Foundation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Foundation> FoundationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Foundation>("ProjectDesigner.Data.FK_VMS_Foundation", "Foundation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Foundation>("ProjectDesigner.Data.FK_VMS_Foundation", "Foundation", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_LEDModule", "LEDModule")]
        public LEDModule LEDModule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LEDModule>("ProjectDesigner.Data.FK_VMS_LEDModule", "LEDModule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LEDModule>("ProjectDesigner.Data.FK_VMS_LEDModule", "LEDModule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LEDModule> LEDModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LEDModule>("ProjectDesigner.Data.FK_VMS_LEDModule", "LEDModule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LEDModule>("ProjectDesigner.Data.FK_VMS_LEDModule", "LEDModule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectDesigner.Data", "FK_VMS_Pillar", "Pillar")]
        public Pillar Pillar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pillar>("ProjectDesigner.Data.FK_VMS_Pillar", "Pillar").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pillar>("ProjectDesigner.Data.FK_VMS_Pillar", "Pillar").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pillar> PillarReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pillar>("ProjectDesigner.Data.FK_VMS_Pillar", "Pillar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pillar>("ProjectDesigner.Data.FK_VMS_Pillar", "Pillar", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
