//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDesigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Extension { get; set; }
        public string FileName { get; set; }
        public string Tags { get; set; }
        public System.DateTime UploadedTime { get; set; }
        public string Remark { get; set; }
    }
}
