//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDesigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navigator
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Parent_Id { get; set; }
        public string LayoutName { get; set; }
        public string WebLink { get; set; }
        public string WinLink { get; set; }
        public string WapLink { get; set; }
        public string Parameters { get; set; }
        public int SortIndex { get; set; }
        public string IconFile { get; set; }
    }
}
