//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDesigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pillar
    {
        public Pillar()
        {
            this.VMS = new HashSet<VMS>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Diameter { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<int> EquipmentType { get; set; }
    
        public virtual ICollection<VMS> VMS { get; set; }
    }
}
