//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDesigner.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectEquipment = new HashSet<ProjectEquipment>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Equipments { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual ICollection<ProjectEquipment> ProjectEquipment { get; set; }
    }
}
